"""Detection signals + confidence scoring (planning.md §1, §2).

Three independent signals, each returning a probability the text is AI-generated
in [0, 1]:

  Signal 1  groq_signal()        — semantic (LLM judgement)
  Signal 2  stylometric_signal() — structural/statistical (burstiness, TTR, …)
  Signal 3  lexical_signal()     — surface/formulaic (AI-cliché phrases, contractions)

combine_signals() blends them with the weights in config.WEIGHTS, derives a
disagreement-aware confidence, and applies the asymmetric verdict thresholds.

Every signal is written so it NEVER raises — a failure degrades gracefully
rather than 500-ing the endpoint (planning.md "Graceful Groq degradation").
"""

import json
import os
import re
import statistics

from groq import Groq

from config import (
    AI_THRESHOLD,
    DISAGREEMENT_MAX,
    GROQ_MODEL,
    HUMAN_THRESHOLD,
    SHORT_TEXT_WORDS,
    WEIGHTS,
)


def _clamp(x, lo=0.0, hi=1.0):
    return max(lo, min(hi, x))


# ============================================================================
# Signal 1 — Groq LLM (semantic)
# ============================================================================

_SYSTEM_PROMPT = (
    "You are a forensic linguist that estimates whether a piece of text was "
    "written by a human or generated by an AI language model. You judge holistically: "
    "semantic coherence, idea flow, originality, and the presence of generic, formulaic "
    "phrasing.\n\n"
    "CRITICAL CALIBRATION RULE: formality, sophistication, complex vocabulary, academic "
    "tone, or non-native phrasing are NOT by themselves evidence of AI authorship — many "
    "humans write that way. Do NOT raise your estimate on formality or polish alone. Only "
    "lean toward AI when you see actual AI hallmarks: hedging boilerplate ('it is important "
    "to note'), empty transitions used as filler ('furthermore', 'moreover'), listy or "
    "templated structure, uniform enthusiasm, vague claims with no concrete specifics, or "
    "an absence of genuine personal voice. Texts with specific domain content, real detail, "
    "or a distinct individual perspective should lean human even when formal.\n\n"
    "On a writing platform, wrongly accusing a human is worse than missing AI text. When "
    "genuinely unsure, return a value near 0.5 rather than a confident accusation."
)

_USER_PROMPT = (
    "Assess the following text and respond ONLY with a JSON object of the form:\n"
    '{{"p_ai_generated": <float 0..1>, "rationale": "<one or two sentences>"}}\n'
    "where p_ai_generated is your probability the text was AI-generated "
    "(0 = clearly human, 1 = clearly AI).\n\n"
    "TEXT:\n\"\"\"\n{text}\n\"\"\""
)


def groq_signal(text):
    """Return {'p_llm': float|None, 'rationale': str, 'degraded': bool}."""
    api_key = os.environ.get("GROQ_API_KEY")
    if not api_key or api_key == "your_key_here":
        return {"p_llm": None, "rationale": "GROQ_API_KEY not configured", "degraded": True}

    try:
        client = Groq(api_key=api_key)
        resp = client.chat.completions.create(
            model=GROQ_MODEL,
            temperature=0,
            response_format={"type": "json_object"},
            messages=[
                {"role": "system", "content": _SYSTEM_PROMPT},
                {"role": "user", "content": _USER_PROMPT.format(text=text)},
            ],
        )
        data = json.loads(resp.choices[0].message.content)
        p = _clamp(float(data.get("p_ai_generated")))
        rationale = str(data.get("rationale", "")).strip()
        return {"p_llm": p, "rationale": rationale, "degraded": False}
    except Exception as exc:  # noqa: BLE001 - signal must never raise
        return {"p_llm": None, "rationale": f"groq_signal error: {exc}", "degraded": True}


# ============================================================================
# Signal 2 — Stylometric heuristics (structural / statistical)
# ============================================================================
# Property: AI prose tends to be UNIFORM — even sentence lengths (low burstiness),
# steady long sentences. Human writing is more variable. We map a few measurable
# statistics to an AI-likeness sub-score, then average. Higher => more AI-like.

_WORD_RE = re.compile(r"[A-Za-z']+")
_SENT_SPLIT_RE = re.compile(r"[.!?]+")
_PUNCT_RE = re.compile(r"[.,;:!?\-—()\"]")


def stylometric_signal(text):
    """Return {'p_style': float, 'metrics': {...}}."""
    words = _WORD_RE.findall(text.lower())
    n_words = len(words)
    sentences = [s for s in _SENT_SPLIT_RE.split(text) if s.strip()]
    sent_lengths = [len(s.split()) for s in sentences] or [n_words or 1]

    mean_len = statistics.mean(sent_lengths)
    stdev_len = statistics.pstdev(sent_lengths) if len(sent_lengths) > 1 else 0.0
    burstiness = stdev_len / mean_len if mean_len > 0 else 0.0  # coeff. of variation
    ttr = len(set(words)) / n_words if n_words else 0.0          # vocab diversity
    punct_density = len(_PUNCT_RE.findall(text)) / n_words if n_words else 0.0

    # Sub-scores (each in [0,1], higher = more AI-like).
    # TTR is computed and reported but NOT scored: on short submissions it sits
    # ~0.85 for human AND AI text, so it carries no signal (see README/limitations).
    ai_burst = _clamp((0.62 - burstiness) / 0.45)     # low variance => AI
    ai_meanlen = _clamp((mean_len - 10) / 14.0)       # long, even sentences => AI

    p_style = _clamp(0.60 * ai_burst + 0.40 * ai_meanlen)

    return {
        "p_style": round(p_style, 3),
        "metrics": {
            "mean_sentence_length": round(mean_len, 2),
            "sentence_length_burstiness": round(burstiness, 3),
            "type_token_ratio": round(ttr, 3),
            "punctuation_density": round(punct_density, 3),
            "n_sentences": len(sentences),
            "sub_scores": {
                "ai_burst": round(ai_burst, 3),
                "ai_meanlen": round(ai_meanlen, 3),
            },
        },
    }


# ============================================================================
# Signal 3 — Lexical-register heuristics (surface / formulaic)
# ============================================================================
# Property: AI text leans on formulaic transitions and avoids contractions/slang.
# We measure cliché-phrase density, contraction rate, and informal markers.
# Higher => more AI-like.

_AI_CLICHES = [
    "furthermore", "moreover", "in conclusion", "it is important to note",
    "it is worth noting", "it is essential", "equally essential",
    "paradigm shift", "delve into", "in today's", "in the realm of",
    "navigate the", "tapestry", "underscore", "pivotal", "crucial role",
    "plays a vital role", "transformative", "stakeholders", "leverage",
    "robust", "seamless", "holistic", "multifaceted", "ever-evolving",
    "essential to consider", "various sectors", "comprehensive",
]

_CONTRACTION_RE = re.compile(
    r"\b\w+'(?:t|s|re|ve|ll|d|m)\b|\b(?:won't|can't|don't|isn't|aren't|didn't|"
    r"wouldn't|couldn't|shouldn't|i'm|it's|that's|there's)\b",
    re.IGNORECASE,
)

_INFORMAL_MARKERS = [
    "ok so", "honestly", "lol", "kinda", "gonna", "wanna", "yeah", "nah",
    "tbh", "imo", "btw", "like, ", "lowkey", "ngl",
]
_ALLCAPS_RE = re.compile(r"\b[A-Z]{3,}\b")          # WAY, OMG (emphasis)
_REPEAT_PUNCT_RE = re.compile(r"[!?]{2,}|\?!|!\?")  # ?!, !!!


def lexical_signal(text):
    """Return {'p_lex': float, 'metrics': {...}}."""
    lowered = text.lower()
    words = _WORD_RE.findall(lowered)
    n_words = max(1, len(words))
    sentences = [s for s in _SENT_SPLIT_RE.split(text) if s.strip()]
    n_sent = max(1, len(sentences))

    cliche_hits = sum(lowered.count(phrase) for phrase in _AI_CLICHES)
    contractions = len(_CONTRACTION_RE.findall(text))
    informal_hits = (
        sum(lowered.count(m) for m in _INFORMAL_MARKERS)
        + len(_ALLCAPS_RE.findall(text))
        + len(_REPEAT_PUNCT_RE.findall(text))
    )

    # Sub-scores (each in [0,1], higher = more AI-like)
    ai_cliche = _clamp(cliche_hits / 2.0)                       # 2+ cliches => max
    contraction_rate = contractions / n_sent
    ai_nocontract = _clamp(1 - contraction_rate * 1.5)         # no contractions => AI
    informal_density = informal_hits / (n_words / 50.0)        # per 50 words
    ai_formal = _clamp(1 - informal_density * 0.6)             # no slang => AI

    p_lex = _clamp(0.45 * ai_cliche + 0.30 * ai_nocontract + 0.25 * ai_formal)

    return {
        "p_lex": round(p_lex, 3),
        "metrics": {
            "cliche_hits": cliche_hits,
            "contractions": contractions,
            "informal_markers": informal_hits,
            "sub_scores": {
                "ai_cliche": round(ai_cliche, 3),
                "ai_nocontract": round(ai_nocontract, 3),
                "ai_formal": round(ai_formal, 3),
            },
        },
    }


# ============================================================================
# Multi-modal — image metadata signal (stretch S4, planning.md)
# ============================================================================
# A second content type: structured image metadata. Generative tools usually
# leave fingerprints (a software/generator tag, an embedded text-to-image prompt,
# or a C2PA content credential). This signal reads those fields; the description/
# alt-text is still run through the stylometric + lexical text signals upstream.

_AI_IMAGE_GENERATORS = [
    "dall-e", "dalle", "midjourney", "stable diffusion", "stablediffusion",
    "firefly", "adobe firefly", "imagen", "ideogram", "flux", "leonardo",
    "nightcafe", "craiyon", "gan", "generative",
]


def metadata_signal(metadata):
    """Return {'p_meta': float, 'reason': str} from image metadata fields.

    `metadata` is a dict that may contain: software/generator (str),
    prompt (str), has_c2pa (bool).
    """
    blob = " ".join(
        str(metadata.get(k, "")) for k in ("software", "generator", "tool", "model")
    ).lower()
    hits = [g for g in _AI_IMAGE_GENERATORS if g in blob]
    if hits:
        return {"p_meta": 0.95, "reason": f"generator/software tag names an AI tool: {hits}"}
    if metadata.get("prompt"):
        return {"p_meta": 0.90, "reason": "metadata embeds a text-to-image generation prompt"}
    if metadata.get("has_c2pa") is True:
        return {"p_meta": 0.80, "reason": "C2PA content credential asserts AI generation"}
    if metadata.get("has_c2pa") is False or blob.strip():
        return {"p_meta": 0.25, "reason": "camera/editor metadata present, no AI generator markers"}
    return {"p_meta": 0.50, "reason": "insufficient metadata to judge provenance"}


def combine_metadata(p_meta, p_style, p_lex, word_count):
    """Blend the metadata signal (dominant) with text signals on the description.

    Metadata is decisive for images, so it carries most of the weight; the
    description text signals nudge it. Reuses the same confidence/verdict shape
    as combine_signals so labels/appeals/audit-log work unchanged downstream.
    """
    if p_style is not None and p_lex is not None and word_count > 0:
        p_ai = 0.70 * p_meta + 0.15 * p_style + 0.15 * p_lex
        components = [p_meta, p_style, p_lex]
    else:
        p_ai = p_meta
        components = [p_meta]

    disagreement = statistics.pstdev(components) if len(components) > 1 else 0.0
    confidence = _clamp(2 * abs(p_ai - 0.5) * (1 - disagreement))

    if disagreement > DISAGREEMENT_MAX:
        attribution = "uncertain"
    elif p_ai >= AI_THRESHOLD:
        attribution = "likely_ai"
    elif p_ai <= HUMAN_THRESHOLD:
        attribution = "likely_human"
    else:
        attribution = "uncertain"

    return {
        "p_ai": round(p_ai, 3),
        "confidence": round(confidence, 3),
        "disagreement": round(disagreement, 3),
        "attribution": attribution,
        "low_evidence": False,
    }


# ============================================================================
# Confidence scoring — combine the three signals (planning.md §2)
# ============================================================================


def combine_signals(p_llm, p_style, p_lex, word_count, degraded):
    """Blend signals into p_ai + a disagreement-aware confidence, then apply the
    asymmetric verdict thresholds.

    Returns a dict: p_ai, confidence, disagreement, attribution, low_evidence.
    """
    if degraded or p_llm is None:
        # Groq unavailable: re-normalize over the two offline signals and cap
        # confidence — we are inherently less sure without the semantic view.
        total = WEIGHTS["style"] + WEIGHTS["lex"]
        p_ai = (WEIGHTS["style"] * p_style + WEIGHTS["lex"] * p_lex) / total
        components = [p_style, p_lex]
        confidence_cap = 0.60
    else:
        p_ai = (
            WEIGHTS["llm"] * p_llm
            + WEIGHTS["style"] * p_style
            + WEIGHTS["lex"] * p_lex
        )
        components = [p_llm, p_style, p_lex]
        confidence_cap = 1.0

    # disagreement: how much the signals contradict each other (0 = unanimous).
    disagreement = statistics.pstdev(components) if len(components) > 1 else 0.0

    # confidence: distance from the 0.5 coin-flip, damped when signals disagree.
    # 0.0 = a coin flip / signals at war; ~1.0 = unanimous and extreme.
    confidence = _clamp(2 * abs(p_ai - 0.5) * (1 - disagreement))
    confidence = min(confidence, confidence_cap)

    # --- verdict (asymmetric p_ai bands + honesty overrides) ---
    low_evidence = word_count < SHORT_TEXT_WORDS
    if low_evidence:
        attribution = "uncertain"                       # short-text guard
    elif disagreement > DISAGREEMENT_MAX:
        attribution = "uncertain"                       # signals at war -> stay honest
    elif p_ai >= AI_THRESHOLD:
        attribution = "likely_ai"                       # high bar to accuse a human
    elif p_ai <= HUMAN_THRESHOLD:
        attribution = "likely_human"                    # easier to clear
    else:
        attribution = "uncertain"

    return {
        "p_ai": round(p_ai, 3),
        "confidence": round(confidence, 3),
        "disagreement": round(disagreement, 3),
        "attribution": attribution,
        "low_evidence": low_evidence,
    }
