"""Detection signals (planning.md §1).

Milestone 3 implements Signal 1 only: the Groq LLM classifier. It returns a
probability that the text is AI-generated (`p_llm` in [0, 1]) plus a short
rationale. Signals 2 (stylometric) and 3 (lexical) arrive in Milestone 4.

Design note: the signal NEVER raises. If the Groq call fails (missing key,
network, bad JSON) it returns p_llm=None and degraded=True, so the endpoint can
degrade gracefully instead of 500-ing (planning.md "Graceful Groq degradation").
"""

import json
import os

from groq import Groq

from config import GROQ_MODEL

_SYSTEM_PROMPT = (
    "You are a forensic linguist that estimates whether a piece of text was "
    "written by a human or generated by an AI language model. You judge holistically: "
    "semantic coherence, idea flow, register, originality, and the presence of generic, "
    "formulaic phrasing. You are calibrated and cautious — on a writing platform, wrongly "
    "accusing a human is worse than missing AI text, so only output high probabilities when "
    "the signs are strong."
)

_USER_PROMPT = (
    "Assess the following text and respond ONLY with a JSON object of the form:\n"
    '{{"p_ai_generated": <float 0..1>, "rationale": "<one or two sentences>"}}\n'
    "where p_ai_generated is your probability the text was AI-generated "
    "(0 = clearly human, 1 = clearly AI).\n\n"
    "TEXT:\n\"\"\"\n{text}\n\"\"\""
)


def groq_signal(text):
    """Return {'p_llm': float|None, 'rationale': str, 'degraded': bool}."""
    api_key = os.environ.get("GROQ_API_KEY")
    if not api_key or api_key == "your_key_here":
        return {"p_llm": None, "rationale": "GROQ_API_KEY not configured", "degraded": True}

    try:
        client = Groq(api_key=api_key)
        resp = client.chat.completions.create(
            model=GROQ_MODEL,
            temperature=0,
            response_format={"type": "json_object"},
            messages=[
                {"role": "system", "content": _SYSTEM_PROMPT},
                {"role": "user", "content": _USER_PROMPT.format(text=text)},
            ],
        )
        data = json.loads(resp.choices[0].message.content)
        p = float(data.get("p_ai_generated"))
        p = max(0.0, min(1.0, p))  # clamp defensively
        rationale = str(data.get("rationale", "")).strip()
        return {"p_llm": p, "rationale": rationale, "degraded": False}
    except Exception as exc:  # noqa: BLE001 - signal must never raise
        return {"p_llm": None, "rationale": f"groq_signal error: {exc}", "degraded": True}


# --- Milestone 3 placeholder scoring ------------------------------------------
# Real multi-signal confidence scoring lands in Milestone 4 (planning.md §2).
# For now, derive a provisional attribution from the single LLM signal so the
# /submit response is inspectable end-to-end. confidence is a PLACEHOLDER.
from config import AI_THRESHOLD, HUMAN_THRESHOLD, SHORT_TEXT_WORDS


def placeholder_score(p_llm, word_count):
    """Provisional verdict from Signal 1 alone. Returns (attribution, confidence)."""
    if word_count < SHORT_TEXT_WORDS or p_llm is None:
        return "uncertain", None
    if p_llm >= AI_THRESHOLD:
        attribution = "likely_ai"
    elif p_llm <= HUMAN_THRESHOLD:
        attribution = "likely_human"
    else:
        attribution = "uncertain"
    # Placeholder confidence: distance from 0.5, scaled to [0,1]. Replaced in M4.
    confidence = round(2 * abs(p_llm - 0.5), 2)
    return attribution, confidence
