"""Transparency label generation (planning.md §3).

Maps a verdict + scores to the plain-language label a reader sees on the platform.
There are exactly three variants, keyed by the verdict:

  likely_ai     -> high-confidence AI label
  likely_human  -> high-confidence human label
  uncertain     -> uncertain label

Design choice (UX): the percentage shown is the DIRECTIONAL LIKELIHOOD
(round(p_ai*100) for AI, round((1-p_ai)*100) for human), not the internal
`confidence` distance-metric. Showing "Likely AI-generated (confidence 36%)"
would read as self-contradictory to a non-technical reader; "~73% likelihood it
was AI-assisted" is clear. The internal `confidence` still decides which verdict
fired upstream and is recorded in the audit log.
"""


_VERIFIED_BADGE = (
    "✅ Verified Human Creator — this creator completed an identity/authorship "
    "verification step. (Detection still runs; the badge is provenance context, "
    "not an exemption.) "
)


def generate_label(attribution, p_ai, confidence=None, verified_creator=False):
    """Return {'variant': str, 'text': str} for the given verdict.

    If `verified_creator` is True, a Verified-Human badge is prepended (stretch S2).
    """
    label = _build_label(attribution, p_ai)
    if verified_creator:
        label["text"] = _VERIFIED_BADGE + label["text"]
        label["verified_creator"] = True
    return label


def _build_label(attribution, p_ai):
    pct_ai = round((p_ai or 0.0) * 100)
    pct_human = round((1 - (p_ai or 0.0)) * 100)

    if attribution == "likely_ai":
        return {
            "variant": "high_confidence_ai",
            "text": (
                f"🤖 Likely AI-generated — Our automated analysis estimates a "
                f"{pct_ai}% likelihood that this content was created with help from "
                f"AI tools. This is an automated estimate, not a verdict of fact, and "
                f"it can be wrong. If you are the creator and disagree, you can appeal "
                f"this assessment."
            ),
        }

    if attribution == "likely_human":
        return {
            "variant": "high_confidence_human",
            "text": (
                f"✍️ Likely human-written — Our automated analysis found no strong "
                f"signs of AI generation in this content (about a {pct_human}% "
                f"likelihood it was written by a human). This is an automated estimate "
                f"and can still be wrong."
            ),
        }

    # uncertain (covers low confidence, signal disagreement, and short text)
    return {
        "variant": "uncertain",
        "text": (
            "❓ Attribution uncertain — We could not confidently determine whether "
            "this content was written by a human or generated by AI, so we are not "
            "making a claim either way. We are telling you this honestly rather than "
            "guessing. No AI-generation claim is being made about this work."
        ),
    }
